project_id = "yyeypbfdtitxqssvnagy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://lovable.dev/projects/c29f3e89-e43a-4ff1-8b01-1c1e6b7b5b61"
additional_redirect_urls = ["https://lovable.dev/projects/c29f3e89-e43a-4ff1-8b01-1c1e6b7b5b61", "https://yyeypbfdtitxqssvnagy.supabase.co"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ins = false

[functions.create-profiles-table]
verify_jwt = false

[functions.verify-totp]
verify_jwt = true

[functions.setup-totp]
verify_jwt = true

[functions.disable-totp]
verify_jwt = true
